
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring
spec:
  template:
    spec:
      containers:
        - image: docker.io/marianemuniz/spring
          imagePullPolicy: Always
