
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: docker.io/marianemuniz/spring
          imagePullPolicy: Always
